receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 180
    spike_limit_mib: 40
  batch: {}

exporters:
  debug:
    verbosity: normal
  file:
    path: /var/log/otel/logs.json
    rotation:
      max_megabytes: 50
      max_days: 3
      max_backups: 10
      localtime: true

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug, file]
  telemetry:
    logs:
      level: info
